name = "github-gemini-agent"
account_id = "95f23a03d74166011160da107f74c055"
main = "worker.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Static assets if using Cloudflare Pages / Workers Sites
# [site]
# bucket = "./dist"
